apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: test-model-server 
  janus-idp.io/tekton: test-model-server
  backstage.io/kubernetes-id: test-model-server
  backstage.io/kubernetes-namespace: rhdh-app 
  app.kubernetes.io/part-of: test-model-server
resources: 
- application-dev.yaml