apiVersion: apps/v1
kind: Deployment
metadata:
  labels: 
    app.kubernetes.io/instance: test-model-server-model-server
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  test-model-server-model-server
    app.kubernetes.io/part-of: test-model-server  
  name: test-model-server-model-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  test-model-server-model-server 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  test-model-server-model-server
    spec:
      containers:
      - image: quay.io/redhat-ai-dev/vllm-openai-ubi9:v0.6.4
        args: [
            "--model",
            "ibm-granite/granite-3.0-8b-instruct",
            "--port",
            "8001",
            "--download-dir",
            "/models-cache",
            "--max-model-len",
            "4097"]
        resources:
          limits:
            nvidia.com/gpu: '1'
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
        - name: models-cache
          mountPath: /models-cache
        name: app-model-service
        ports:
        - containerPort: 8002
        securityContext:
          runAsNonRoot: true
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory
          sizeLimit: "2Gi"
      - name: models-cache
        persistentVolumeClaim:
          claimName: test-model-server

      tolerations:
        - key: nvidia.com/gpu
          operator: Exists
          effect: NoSchedule
