apiVersion: v1
kind: ConfigMap
metadata:
  name: test-model-server-model-config
data:
  MODEL_ENDPOINT: "http://test-model-server-model-server:8001"
  MODEL_NAME: "ibm-granite/granite-3.0-8b-instruct"